### ISSUE TITLE
Broken links 2022

### ISSUE THREAD

**Issue by hkhdair** [dangkhoasdc/awesome-ai-residency#32]
Links for 2022 need to be updated:

Facebook AI Residency Program (https://www.facebookcareers.com/jobs/221246603377392/)
Apple AI Residency Program (https://machinelearning.apple.com/updates/aiml-residency-program-application-2022).
Anthropic (https://jobs.lever.co/Anthropic/6fdef6f7-b3fe-4a5b-b504-aea0c12168d3)

broken links or programs do not currently exist.

Thanks,

**Comment by dangkhoasdc** [comment]
> Links for 2022 need to be updated:
> 
> Facebook AI Residency Program (https://www.facebookcareers.com/jobs/221246603377392/) Apple AI Residency Program (https://machinelearning.apple.com/updates/aiml-residency-program-application-2022). Anthropic (https://jobs.lever.co/Anthropic/6fdef6f7-b3fe-4a5b-b504-aea0c12168d3)
> 
> broken links or programs do not currently exist.
> 
> Thanks,

Thanks, I checked and updated accordingly. Anthropic program is still available.
